version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: route_planner_api
    restart: always
    ports:
      - "3008:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - ENV=prod
    networks:
      - route_planner_network
    depends_on:
        - mysql

  mysql:
    image: mysql:8
    restart: always
    container_name: route_planner_mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: route_planner
      MYSQL_USER: route_planner
      MYSQL_PASSWORD: route_planner
      MYSQL_ROOT_PASSWORD: route_planner
    networks:
      - route_planner_network
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:

networks:
  route_planner_network: