name: Deploy to Production

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: route-planner

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Run tests
        run: go test -v ./...

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/app/route-planner
            # Pull the latest changes
            git pull
            
            # Copy environment variables if needed
            echo "${{ secrets.ENV_FILE }}" > .env
            
            # Build and start the containers
            docker-compose up --build -d
